### PR TITLE
7.x 1.3

### PR DESCRIPTION
**Pull request by MorganDawe**
Submitting cleanup for release.

### CODE REVIEW

**Comment by willtp87** [comment]
No, #51 was killed in favor of this pull request that only contains Morgan's fixes from #50 not pull request #47 from Alan.

**Comment by willtp87** [comment]
I have updated our documentation.  Please review https://github.com/Islandora/islandora/wiki/How-Islandora-Code-gets-Made/_compare/e78a9c3e1d7a191b4551888dcb8ce2332a76d2cd...244642c002d76b08c73ae6e86f6503b651b192b2

**Comment by mjordan** [comment]
@ruebot looks good. Not sure if you want to make the "who can merge pull requests" protocol explicit (maybe under a different heading such as "GitHub Workflows") but some of us need to be told repeatedly :hammer:

**Comment by willtp87** [comment]
I's better than what it was :). I'd like to see this page merged in some way with the git workflow page someday, the separation is less than clear and I find the organization of these pages unintuitive.  I skimmed through our wiki as well and noticed a few out of date things.  This template page is still using the old format: https://github.com/Islandora/islandora/wiki/Readme-template is there a template for the new format that we can update this with?  Also I think this page should be destroyed: https://github.com/Islandora/islandora/wiki/Policies

**Comment by jordandukart** [comment]
Hey @ruebot, Will sits literally one foot beside me and I okayed this merge.

**Pull request merged**
